### ISSUE TITLE
Electron or tkinter

### ISSUE THREAD

**Issue by jacobhq** [Diacius/pos#8]
Should we use electron or tkinter?

**Comment by Diacius** [comment]
Electron. TK is a pain
________________________________
From: Jacob Marshall ***@***.***>
Sent: Tuesday, March 23, 2021 12:29 pm
To: Diacius/pos
Cc: Subscribed
Subject: [Diacius/pos] Electron or tkinter (#8)


Should we use electron or tkinter?
